### PR TITLE
Fixed some problems in using container clusters of both amd64 and arm…

### PR DESCRIPTION
**Pull request by s5u-ishida**
… CPU architecture with K8s 1.13.2 and DockerCE 18.9.1.

- deployed to amd64 using nodeSelector.
- fixed "Kubernetes Pod Resources" -> "Cpu Usage" displayed as "No Data".
- fixed "Prometheus Stats" -> "Uptime" displayed as "No Data".
- fixed that "Prometheus Stats" -> "Rule Eval Duration" is displayed as "No Data".

I am pleased if this change is worth merging into your master.

### CODE REVIEW

**Comment by pipo02mix** [comment]
Why do you want to explicitly add `beta.kubernetes.io/arch` equal to `amd64`?

Can you add the grafana fixes in the helm folder too?

Thanks for contributing

**Comment by s5u-ishida** [comment]
> Why do you want to explicitly add `beta.kubernetes.io/arch` equal to `amd64`?

I am constructing a multi-architecture container cluster with Kubernetes consisting of amd64 CPU VMs on the AWS or on-premise, and arm CPU machines on the edge.

In this environment,
```
kubectl apply -f manifests-all.yaml
```
Then these containers may be deployed to the arm machine and fail. Therefore, I added conditions for deployment limited to amd64 nodes.

> Can you add the grafana fixes in the helm folder too?

Sorry, I do not know helm because I do not use it.

**Comment by pipo02mix** [comment]
Well I think the `arch` selector is something optional and I would not like to add it as default. If you use the helm package it can be selectable, but in the plain manifest is not possible.

I am ok with the grafana changes

**Comment by s5u-ishida** [comment]
I understood not applying nodeSelector. Thank you for confirming the change to grafana.

**Pull request merged**
